# image base

FROM node:20-alpine

WORKDIR /app
# Todos los paquetes json
COPY package*.json ./
RUN npm install
# Copiar el codigo fuente
COPY . .
#Exponer el puerto de desarrollo deSvelteKit

#Comando para modo desarrollo
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 5173
ENTRYPOINT ["/entrypoint.sh"]

