# image base

FROM node:20-alpine

WORKDIR /app
# Todos los paquetes json
COPY package*.json ./
RUN npm install
# Copiar el codigo fuente
COPY . .
#Exponer el puerto de desarrollo deSvelteKit
EXPOSE 5173

#Comando para modo desarrollo

CMD ["npm,"run","dev","--","--host"]

