# Version de node
FROM node:20-alpine AS builder
# Mi carpeta raiz dentro del contenedor
WORKDIR /app
# Copia todos los package json a raiz
COPY package*.json ./

# se instalana las dependencias del manifiesoto

RUN npm install

#Copiamos el resto del codigo

COPY . .


#Etapa final
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

#Comando por defecto 
CMD ["npm","start"]
